## 公共配置
log:
  level: debug
  path: /Users/luoguochun/.config/bbq/logs/
  file: trade.log
mongo:
  uri: mongodb://localhost:27017/
  pool: 5
mysql:
  uri: mysql+pymysql://bbq:bbq@localhost/bbq
message:
  email:
    host: smtp.126.com
    port: 465
    email: barbarianquant@126.com
    secret: DAZXJPKTVXRVOESQ
  wechat:
    token: SCT79912TBBpSAKVv98IdQ3RWqCoQQNW2
monitor:
  strategy-path:
    - /Users/luoguochun/.config/bbq/strategy/monitor
  strategy:
    - id: builtin:Dummy
      option: null
trade:
  strategy-path:
    broker:
      - /Users/luoguochun/.config/bbq/strategy/broker
    trade:
      - /Users/luoguochun/.config/bbq/strategy/trade
    risk:
      - /Users/luoguochun/.config/bbq/strategy/risk
  strategy:
    # 策略名称
    id: builtin:Dummy
    option: null
  # 账户id
  account-id: my-debug-account
  # 初始资金
  init-cash: 100000
  broker-fee: 0.00025
  transfer-fee: 0.00002
  tax-fee: 0.001
  # 交易品类 stock / fund
  category: stock
  # 交易类型 real / simulate / backtest
  type: backtest
  quotation:
    frequency: 1d
    codes:
      - sh000001
      - sh601618
    # 回测时用 yyyy-mm-dd HH:MM:SS
    start-date: 2020-12-01
    end-date: 2020-12-31
  risk:
    id: builtin:Dummy
    option: null
#  broker:
#    id: builtin:BrokerGitee
#    option:
#      token: a61f482097e041c30e05327fb8b0a2ae
#      owner: heidonglgc
#      repo: bbq-broker
#      timeout: 3
  broker:
    id: builtin:BrokerSimulate
    option:
      token: a61f482097e041c30e05327fb8b0a2ae
      owner: heidonglgc
      repo: bbq-broker
      timeout: 3
